spring:
  servlet:
    multipart:
      max-file-size: 10MB # 업로드할 수 있는 개별 파일의 최대 크기. 기본 1MB
      max-request-size: 10MB # multipart/form-data 요청의 최대 허용 크기. 기본 10MB

  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  config:
    import: optional:file:.env[.properties],optional:aws-secretsmanager:/fixi/application-secrets

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jwt:
    issuer: sanhagteamplace@gmail.com
    secret_key: teamplace-fixi

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

  rabbitmq:
    host: ${RABBITMQ_URL}
    port: 5671
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    ssl:
      enabled: true
