spring:
  servlet:
    multipart:
      max-file-size: 10MB # 업로드할 수 있는 개별 파일의 최대 크기. 기본 1MB
      max-request-size: 10MB # multipart/form-data 요청의 최대 허용 크기. 기본 10MB

  jpa:
    #    hibernate:
    #      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  config:
    import: 'aws-secretsmanager:/fixi/application-secrets'

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jwt:
    issuer: ${JWT_ISSUER}
    secret_key: ${JWT_SECRET}

  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: guest
  #    password: guest

  rabbitmq:
    host: ${RABBITMQ_URL}
    port: 5671
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    ssl:
      enabled: true

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
    stack:
      auto: false

paypal:
  return-url: ${RETURN_URL}
  cancel-url: ${CANCEL_URL}
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}